[package]
name = "cdr-encoding-size-derive"
version = "0.1.0"
edition = "2018"
authors = ["Juhana Helovuo <juhe@iki.fi>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

